version: '3.8'

services:
  # Aplicación Spring Boot
  backend:
    # Construir desde el Dockerfile existente
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      # Activar perfil local
      - SPRING_PROFILES_ACTIVE=local
      # Configuración específica para Docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5432/fisio_db
    volumes:
      # Montar directorio de uploads para persistencia
      - ./uploads:/app/uploads
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - fisio-network

  # Base de datos PostgreSQL local
  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: fisio_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - fisio-network

  # Aplicación frontend (opcional)
  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "5173:5173"
  #   depends_on:
  #     - backend
  #   environment:
  #     - VITE_API_URL=http://localhost:8080
  #   networks:
  #     - fisio-network

volumes:
  postgres-data:
    driver: local

networks:
  fisio-network:
    driver: bridge 